version: "3.9"
services:
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
  database:
    image: "postgres:14.2"
    volumes:
      - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
volumes:
  coder_data:
